### ISSUE TITLE
Theme not rendering correctly under linux

### ISSUE THREAD

**Issue by phisch** [saadq/Materialize-Appbar#2]
The sidebar with the file-tree and the bottom bars are not being rendered correctly when this theme is enabled. Here is a screenshot to demonstrate what i am talking about:
![image](https://cloud.githubusercontent.com/assets/1282767/13960253/dc3d5a98-f057-11e5-99dc-2d04aaada390.png)

I am running the latest SublimeText build 3109, on Ubuntu.

The theme looks really nice on the screenshots, so let me know if you need my assistance!

**Comment by saadq** [comment]
Hey @PhilippSchaffrath,

**Materialize-Appbar** is actually just for that bar at the top of the theme. It is basically an addon for the themes in the [Materialize](https://github.com/saadq/Materialize) package which you will need to install first. Please make sure you have both Materialize and Materialize-Appbar installed!

**Comment by phisch** [comment]
You are absolutely right, i did not have had Materialize installed.
