### ISSUE TITLE
no change in windows 10

### ISSUE THREAD

**Issue by hamedmoody** [saadq/Materialize-Appbar#6]
Hi i installed your package and restarted sublime, but no change happened. what do i do?

**Comment by saadq** [comment]
Do you have [Materialize](https://github.com/saadq/Materialize) installed already? The Appbar is just an addon for the themes you get from installing Materialize.

**Comment by hamedmoody** [comment]
Ok thanks

**Comment by saadq** [comment]
Were you able to get it working after installing Materialize and using one of the themes from it? If so, let me know and I can close this issue.

**Comment by hamedmoody** [comment]
it is work, So thanks
