### ISSUE TITLE
Installation via Package Control on OSX does not change the editor

### ISSUE THREAD

**Issue by beeekind** [saadq/Materialize-Appbar#7]
I installed the package via package control and restarted my editor, but there were no changes. I'm running OSX, the only other package currently installed is Materialize.

The package shows up in preferences/browse packages and can be removed and reinstalled without any changes being seen in sublime.

**Comment by beeekind** [comment]
This issue can be closed, solution can be found @ https://github.com/equinusocio/material-theme-appbar/issues/25

**Comment by saadq** [comment]
Cool. And you can also close issues that you made by pressing the <kbd>Close Issue</kbd> button to the left of the <kbd>Comment</kbd> button :)
